### ISSUE TITLE
Support for JSDoc Block Tags

### ISSUE THREAD

**Issue by alukach** [cdklabs/jsii-docgen#136]
Looking at the CDK official documentation, I noticed there are a number of UI elements produced by [JSDoc block tags](https://jsdoc.app/#block-tags) within its documentation that do not appear in the output of the markdown generated by this library. Running some experiments, I have gathered the following:

| tag | supported? | notes |
| --- | --- | --- |
| `@deprecated` |  partial | `⚠️` symbol is rendered, but text is not |
| `@default` | unsupported | |
| `@see` | unsupported | |

Am I correct that these are not handled by `jsii-docgen`? Is there any way to get these values in the outputted markdown?

An aside: I am realizing I may have been incorrect in assuming that this library is what was used to generate the CDK online documentation.  Is there another library used or is this library heavily modified for that purpose?

**Comment by alukach** [comment]
> An aside: I am realizing I may have been incorrect in assuming that this library is what was used to generate the CDK online documentation. Is there another library used or is this library heavily modified for that purpose?

Rereading [this comment](https://github.com/aws/jsii-docgen/issues/129#issuecomment-728330981), I see now that you've stated that the CDK docs are generated with a different tool (and `jsii-docgen` is a fork of that tool).  Is the original tool's source code public at all?

**Comment by eladb** [comment]
Contributions are welcome!

**Comment by alukach** [comment]
Sounds good.  Some dev notes:

1. Stability is rendered as such:
    https://github.com/aws/jsii-docgen/blob/ff38c24a7dada75b1ea70b104b7360b817a25ebe/src/render/page.ts#L65-L73
1. Output would likely benefit from returning to a `span` tag for its `title` attribute. @eladb do you recall why it was disabled in 239fe1d12f1378afc1fc298741a433d3fbc9651e?
    https://github.com/aws/jsii-docgen/blob/ff38c24a7dada75b1ea70b104b7360b817a25ebe/src/render/page.ts#L206-L209
1. Other properties beyond "stability" could be rendered as well, see [the members of the JSII spec Docs interface](https://github.com/aws/jsii/blob/170b536c6fb29d14ba15e6c65786631a5f4cba70/packages/%40jsii/spec/lib/assembly.ts#L259-L350) for low-hanging fruit.
