### ISSUE TITLE
jsii-docgen fails to produce documentation on Windows due to improper input to find assemblies.

### ISSUE THREAD

**Issue by FreakBurrito** [cdklabs/jsii-docgen#1379]
When running on Windows, node-glob does not resolve any assemblies in the project due to assembliesDir containing Windows style path delimiters.

https://github.com/cdklabs/jsii-docgen/blob/70797a936950d46c3127c8cfcc5118f9a3558a09/src/docgen/view/documentation.ts#L410

According to the Docs for node-glob It should use `/` for path delimiters as `\` is reserved for escaping glob characters.
https://github.com/isaacs/node-glob?tab=readme-ov-file#usage

**Comment by mrgrain** [comment]
Fixed by https://github.com/cdklabs/jsii-docgen/pull/1398
