### ISSUE TITLE
jsii-docgen seems to use javadoc syntax instead of tsdoc

### ISSUE THREAD

**Issue by TimothyJones** [cdklabs/jsii-docgen#1634]
tsdoc and javadoc have slightly different syntax. 

For example, tsdoc [wants a hyphen](https://tsdoc.org/pages/tags/param/) at the start of `@param` descriptions, while javadoc [does not](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDHJECF):

```
tsdoc
 * @param first - The first parameter
javadoc:
 * @param first The first parameter
```

I've got automated tooling to enforce tsdoc syntax, but because jsii-docgen assumes the javadoc syntax, then the documentation ends up with errant `-` characters at the start of each parameter.

Another difference is in links. For example, tsdoc [links](https://tsdoc.org/pages/tags/link/) use `|` to separate the text from the target, but javadoc [does not](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDDIECH).

```
tsdoc   {@link SomeClass | click here}
javadoc {@link SomeClass click here}
```

However, the generated `remarks` sections when using `-l typescript -f json` re-print the links in javadoc syntax, even if the format is `typescript`.

**Comment by mrgrain** [comment]
`jsii-docgen` doesn't parse your TS code, instead it reads from a pre build jsii assembly file (usually `.jsii`).

Can you please post the relevant section from your jsii assembly. If it's already wrong in the assembly, the issue is with aws/jsii-compiler and not jsii-docgen. (And because these repos live in a different organizations we unfortunately cannot move the issue.)

**Comment by TimothyJones** [comment]
Sure thing! I've created [this repository](https://github.com/TimothyJones/jsii-docgen-issue-1633) illustrating both problems. 

The relevant part for this issue is the parsing of [this line](https://github.com/TimothyJones/jsii-docgen-issue-1633/blob/main/src/index.ts#L14):

```
    /**
     * This documents a constructor
     * 
     * @param someParameter - this documents the parameter
     */
```
 
 Which results in [this line in the assembly](https://github.com/TimothyJones/jsii-docgen-issue-1633/blob/main/.jsii#L69), which is from this segment:
 
```
        "parameters": [
          {
            "docs": {
              "summary": "- this documents the parameter."
            },
            "name": "someParameter",
            "type": {
              "primitive": "string"
            }
          }
        ]
```
(note that the `summary` inappropriately starts with `"- "`)

**Comment by TimothyJones** [comment]
Oh, I forgot to include the repro for the link issue - in the generated json documentation for typescript, [this line](https://github.com/TimothyJones/jsii-docgen-issue-1633/blob/main/docs-json/typescript.json#L52) is in javadoc syntax - 

```
{@link https://github.com/cdklabs/jsii-docgen/issues/1634 this link}
```

Which seems odd, as it was originally from a properly formed tsdoc comment [here](https://github.com/TimothyJones/jsii-docgen-issue-1633/blob/main/src/index.ts#L3).

```
{@link https://github.com/cdklabs/jsii-docgen/issues/1634 | this link}
```

I'm not sure if there are other issues like this, these are just the two I noticed.

**Comment by mrgrain** [comment]
> Also, let me know if you want me to reopen these issues somewhere else.

That's a great reproduction. Both look like issues with aws/jsii-compiler.
Thank you that would be great if you could reopen them.

**Comment by TimothyJones** [comment]
Thanks! Opened https://github.com/aws/jsii-compiler/issues/1498 to track this.
