### ISSUE TITLE
Bug: Issue with temporary folder and symlinks

### ISSUE THREAD

**Issue by joostvdwsd** [cdklabs/jsii-docgen#390]
This issue occurs with the following project structure:

```
- root
  - packages
    - jsii project a
      - node_modules/project b -> symlink to project b containing '../../jsii project b'
    - jsii project b
```

jsii-reflect will correctly resolve all types. But jsii-docgen throws:
"Error: Assembly "jsii project b" not found"

This is (probably) due to the fact that the below code is making a full copy of the project structure:

https://github.com/cdklabs/jsii-docgen/blob/f3f0509f114e03274854c4f1d81ac5cf7691730c/src/docgen/view/documentation.ts#L180

The above code will copy the symlink as file to the temporary folder. This symlink will be invalid if its a relative link.

Probably either needs to fix it by not making a copy or to use something like:
```
await fs.copy(assembliesDir, workdir, {
    dereference: true
});
```

The copy also is responsible for a very long execution time due to all dependency copies. Didn't go through all code in the docgen package but it it really needed in this scenario to make a copy? I would think that the generator will not modify any files. Only the generation of the md file. Not copying would also make it possible to work without nohoist for peer dependencies.

This is actually part of a yarn monorepo where I configured the projects with nohoist. I cannot imagine i'm the only one encountering this. Anyone knows a way around it?

**Comment by RichiCoder1** [comment]
I'm also running into this now too, for basically the same case. Docgen fails on any package manager workspace that doesn't full put all files into the workspace's `node_modules`.

**Comment by michanto** [comment]
I this still being worked on?  I am using projen-turborepo and I am seeing this issue.  
`Error: Assembly "constructs" not found`

**Comment by MrArnoldPalmer** [comment]
@michanto yeah I just need to update my PR with the latest jsii-pacmak and it should be good. Should be able to do that shortly.

**Comment by ashby2** [comment]
Hi @MrArnoldPalmer, just checking on this. I can open a PR to fix the build, but wasn't sure where to add `jsii-pacmak` since it appears to be an upstream dependency of other jsii libs?

**Comment by agdimech** [comment]
+1 seeing this with pnpm for the same reasons as mentioned above.

**Comment by agdimech** [comment]
> Hi @MrArnoldPalmer, just checking on this. I can open a PR to fix the build, but wasn't sure where to add `jsii-pacmak` since it appears to be an upstream dependency of other jsii libs?

I think @MrArnoldPalmer meant to say update jsii-rosetta, given this or depends on this PR: https://github.com/aws/jsii/pull/3437

Bumping jsii-rosetta in package.json should resolve the build failure and then should be good to merge.

**Comment by MrArnoldPalmer** [comment]
@agdimech that is correct, however I was wrong and it's a little more nuanced, though I do believe this should still solve most of the issues described in this thread.

See https://github.com/cdklabs/jsii-docgen/pull/644#issuecomment-1150336766 for details.
