### ISSUE TITLE
CLI command only generates docs in root submodule by default

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/jsii-docgen#540]
JSII projects may have multiple submodules (for examples libraries, see `aws-cdk-lib` and `projen`). Currently the CLI only generates docs for the root submodule by default. This appears to be a regression from jsii docgen v0.1.x.

I think the default behavior for both the programmatic API and the CLI should be to render docs for all submodules if no other option has been specified. There should also be a way in the CLI to specify specific submodules to render (to match the `submodule` option available in the programmatic API).

**Comment by webratz** [comment]
Ran into that aswell, are there any workarounds or pointers where to fix that in the code?
