### ISSUE TITLE
Include jsii-rosetta examples

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/jsii-docgen#585]
The AWS CDK API reference includes example code snippets for most constructs, classes, structs, and enums. [Example](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html#example). These are generated from information within jsii "tablet" files (if you install `aws-cdk-lib`, within the package you should find a `.jsii.tabl.json` file).

However, these are not displayed when you generate an API reference with jsii-docgen (and hence, they're not shown on Construct Hub). [Example](https://constructs.dev/packages/aws-cdk-lib/v/2.10.0/api/Bucket?lang=typescript&submodule=aws_s3). We should find a way to include these since many users find them helpful given that CDK is vended in multiple languages.

**Comment by agdimech** [comment]
> The AWS CDK API reference includes example code snippets for most constructs, classes, structs, and enums. [Example](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html#example). These are generated from information within jsii "tablet" files (if you install `aws-cdk-lib`, within the package you should find a `.jsii.tabl.json` file).
> 
> However, these are not displayed when you generate an API reference with jsii-docgen (and hence, they're not shown on Construct Hub). [Example](https://constructs.dev/packages/aws-cdk-lib/v/2.10.0/api/Bucket?lang=typescript&submodule=aws_s3). We should find a way to include these since many users find them helpful given that CDK is vended in multiple languages.

+1

Ideally based on the target language specified in the args to jsii-docgen, it should parse all @example and .md files, run rosetta to generate the tablet and then substitute into the generated docs the language appropriate substitution. This will allow the ability to simply pipe this into something like mkdocs to generate a micro site for any language binding with minimal additional work.

**Comment by agdimech** [comment]
Did a little digging...

It appears https://github.com/cdklabs/jsii-docgen/blob/main/src/docgen/schema.ts#L498 is not adding the example to the returned doc. Additionally in https://github.com/cdklabs/jsii-docgen/blob/main/src/docgen/render/markdown-doc.ts#L104 the doc renderer is not emitting a line for the example. This can be easily fixed by adding the following:

# schema.ts
```ts
function extractDocs(docs: reflect.Docs, language: Language) {
...
    return filterUndefined({
       ...
        example: docs.example.length > 0 ? docs.example : undefined,
        language: language
    });
```

# markdown-doc.ts
```ts
docs(docs) {
    ...
    if (docs.example) {
        this.code(docs.language, docs.example);
    }
}
```
