### ISSUE TITLE
Split pages into groups / classes

### ISSUE THREAD

**Issue by DanielMSchmidt** [cdklabs/jsii-docgen#756]
Hey there, 

We are currently using jsii-docgen to generate our [API documentation](https://www.terraform.io/cdktf/api-reference/typescript).
The problem is that it's all generated on one page, making it very hard to navigate. Having a way to bring a file-structure to the documentation, having a grouping either by class / folder / file / manual grouping would be helpful, it would make the docs more usable for readers.

**Comment by mrgrain** [comment]
We now have `--split-by-submodule`
